apiVersion: v1
kind: Service
metadata:
  name: nginx-php-fpm
  labels:
    name: nginx-php-fpm
    layer: frontend
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 80
     name: http
  externalIPs:
    - 178.79.160.49
    - port: 443
      nodePort: 30443
      name: https
  selector:
    name: nginx-php-fpm
