apiVersion: v1
kind: Service
metadata:
  name: nginx-php-fpm
  labels:
    name: nginx-php-fpm
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32124
      name: http
    - port: 443
      nodePort: 30443
      name: https
  selector:
    name: nginx-php-fpm
