apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-php-fpm
  template:
    metadata:
      labels:
        app: nginx-php-fpm
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-data
              mountPath: /var/website
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
        - name: php-fpm
          image: php:7.3-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: web-data
              mountPath: /var/website
      volumes:
        - name: web-data
          hostPath:
            path: /var/website
            type: Directory
        - name: nginx-config
          configMap:
            name: nginx-config
